### ISSUE TITLE
License

### ISSUE THREAD

**Issue by glyn** [drtconway/permutation-rs#1]
I like the look of the code in this repository, but am put off using it because there is no open source license. (I'm happy to provide a PR to fix this if you just say which license you'd like to use.)

**Comment by drtconway** [comment]
Sure! I'm happy to whack the Apache license on it, if you want to make a PR

**Comment by glyn** [comment]
Thank you @drtconway. You may be interested in the context: https://underlap.org/open-development-experiment-search-for-feistel-networks.

**Comment by drtconway** [comment]
Perhaps I should add to the README. :)

The motivation is straight-forward. There are many applications where we want to process a (large) sequence of things in a randomised order, but we would like to avoid permuting the sequence itself, or storing the entire permutation vector.

An example could be in bioinformatics where we have a few billion short sequences, and we want to cluster them in parallel, in a randomised order. Using this permutation algorithm, so long as we know the seed, we can work out the nth item in the permutation with constant space, and approximately constant time. You can imagine a k-means implementation:

1. pick a random seed to create the permutation
2. take the first k items as the centroids
3. divide up the remaining (large) range into the number of threads
4. in each thread, use the permutation object to iterate over the short sequences

Given that our few billion short sequences (e.g. a u64 each) will take quite a lot of RAM, there is a clear benefit in being able to represent the permutation in constant space.

This idea is not new (see, for example https://doi.org/10.1137/0217022)

**Comment by glyn** [comment]
Very interesting! Yes, a README would be great for others who encounter this project.

**Comment by glyn** [comment]
Thanks @drtconway for writing such a clear README. I've now given up writing my own implementation as yours is just the ticket.
